#  settings
url = "http://localhost:8545"
network = "sokol" # "core" for the main and "sokol" for the test network
timeout = 500000

# mining-block-test settings
maxRounds = 5

# Test accounts
addressFromTxTest = "0x...dfcb"
passwordFromTxTest = "password"
addressToTxTest = "0x...a72"
passwordToTxTest = "password"

addressFromPublicRpcTest = "0x...cb"
passwordFromPublicRpcTest = "password"
addressToPublicRpcTest = "0x....2"
passwordToPublicRpcTest = "password"

# Transaction settings
gasPrice = "1000000000"
simpleTransactionGas = "21000"
simpleTransactionCost = "21000000000000" # equals to gas multipty by gascost: 21000 * 1000000000
amountToSend = "20000000000"
miningReward = "1000000000000000000"
keyStorePath = "\path\a0db34...745f0b.json"
txsNumber = 10

# Reorgs settings
maxBlocksToSave = 20

#slack
slackWebHookUrl = 'https://hooks.slack.com/services/............token'